const STORAGE_KEY='constellation-ip-pins';
const pins=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
const globeDialog=document.getElementById('globeDialog');
const globe=document.getElementById('globe');
const livePin=document.getElementById('livePin');
const status=document.getElementById('saveStatus');
const pinList=document.getElementById('pinList');
const pinCount=document.getElementById('pinCount');
const locationReadout=document.getElementById('locationReadout');
const ipStatus=document.getElementById('ipStatus');
const ipForm=document.getElementById('ipForm');
const dateInput=document.getElementById('dateInput');

dateInput.value=new Date().toISOString().slice(0,10);
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(pins));status.textContent='● saved';renderPins()}
function renderPins(){pinList.innerHTML='';pinCount.textContent=String(pins.length).padStart(2,'0');if(!pins.length){pinList.innerHTML='<div class="empty">No dated signals yet. Add an IP to create the first glowing pin.</div>';return}pins.slice().reverse().forEach((pin,index)=>{const card=document.createElement('article');card.className='pin-card';card.innerHTML=`<span class="pin-meta">${escapeHtml(pin.date)} · ${escapeHtml(pin.ip)}</span><h3>${escapeHtml(pin.label||pin.city||'Signal location')}</h3><p>${escapeHtml(pin.city||'Approximate location unavailable')}${pin.country?`, ${escapeHtml(pin.country)}`:''}<br><small>${escapeHtml(pin.source||'Geolocation lookup')}</small></p>`;card.addEventListener('click',()=>showPin(pin));pinList.appendChild(card)})}
function showPin(pin){const visual=toGlobePosition(pin.latitude,pin.longitude);document.querySelectorAll('.constellation-pin').forEach(el=>el.remove());const marker=document.createElement('button');marker.className='constellation-pin';marker.title=`${pin.ip} · ${pin.date}`;marker.style.left=`${visual.x}%`;marker.style.top=`${visual.y}%`;marker.addEventListener('click',()=>showPin(pin));document.getElementById('constellationPins').appendChild(marker);locationReadout.innerHTML=`<span>${escapeHtml(pin.ip)} · ${escapeHtml(pin.date)}</span><strong>${escapeHtml(pin.city||'Unknown area')}${pin.country?', '+escapeHtml(pin.country):''}</strong>`}
function toGlobePosition(lat,lon){return{x:50+(Number(lon)/180)*38,y:50-(Number(lat)/90)*36}}
function validIp(value){const v=value.trim();const ipv4=/^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/;const ipv6=/^[0-9a-f:]+$/i;return ipv4.test(v)||ipv6.test(v)}
document.getElementById('openGlobe').addEventListener('click',()=>{globeDialog.showModal();document.getElementById('ipInput').focus()});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>globeDialog.close()));document.getElementById('themeToggle').addEventListener('click',()=>document.body.classList.toggle('high-glow'));document.getElementById('exportPins').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(pins,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='constellation-ip-pins.json';a.click();URL.revokeObjectURL(a.href)});
ipForm.addEventListener('submit',async event=>{event.preventDefault();const ip=document.getElementById('ipInput').value.trim();if(!validIp(ip)){ipStatus.textContent='Enter a valid public IPv4 or IPv6 address.';return}ipStatus.textContent='Querying approximate location…';try{const response=await fetch(`https://ipapi.co/${encodeURIComponent(ip)}/json/`);if(!response.ok)throw new Error('Lookup failed');const data=await response.json();if(data.error)throw new Error(data.reason||'Location unavailable');const pin={ip,date:dateInput.value,label:document.getElementById('labelInput').value.trim(),latitude:Number(data.latitude),longitude:Number(data.longitude),city:data.city,country:data.country_name,source:'ipapi.co'};if(!Number.isFinite(pin.latitude)||!Number.isFinite(pin.longitude))throw new Error('No coordinates returned');pins.push(pin);persist();showPin(pin);livePin.classList.add('active');livePin.style.left=`${toGlobePosition(pin.latitude,pin.longitude).x}%`;livePin.style.top=`${toGlobePosition(pin.latitude,pin.longitude).y}%`;ipStatus.textContent='Signal plotted. Location is approximate.';locationReadout.innerHTML=`<span>${escapeHtml(pin.ip)} · ${escapeHtml(pin.date)}</span><strong>${escapeHtml(pin.city||'Unknown area')}${pin.country?', '+escapeHtml(pin.country):''}</strong>`}catch(error){ipStatus.textContent=error.message||'Could not locate that IP.'}});
for(let i=0;i<35;i++){const star=document.createElement('i');star.className='star';star.style.cssText=`left:${Math.random()*98}%;top:${Math.random()*96}%;--s:${Math.random()*3+1}px;animation-delay:${Math.random()*4}s`;document.getElementById('stars').appendChild(star)}
renderPins();pins.forEach(showPin);
